version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.16.4
    parallelism: 2
    steps:
       -run:
         name: Ensure Test Parity
         command: |
            chmod +x jos.sh
            ./jos.sh
